//Redux
export const GET_ERRORS = "GET_ERRORS";

export const GET_TRIPS = "GET_TRIPS";
export const GET_TRIP = "GET_TRIP";
export const GET_TRIP_GROUPS = "GET_TRIP_GROUPS";
export const DELETE_TRIP = "DELETE_TRIP";
export const ADD_TRIP_TO_TRIPGROUP = "ADD_TRIP_TO_TRIPGROUP";
export const DELETE_TRIP_GROUP = "DELETE_TRIP_GROUP";
export const GET_TRIP_TYPE = "GET_TRIP_TYPE";
export const GET_TRIP_TYPES = "GET_TRIP_TYPES";
export const GET_TRIP_GROUP = "GET_TRIP_GROUP";
export const GET_TRIPS_BY_TRIPGROUP = "GET_TRIPS_BY_TRIPGROUP";
export const GET_TRIP_BY_TRIPGROUP = "GET_TRIP_BY_TRIPGROUP";

export const GET_USER_INFO = "GET_USER_INFO";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS_LOCATION = "GET_USERS_LOCATION";

export const GET_PLACES = "GET_PLACES";
export const DELETE_PLACE = "DELETE_PLACE";

export const GET_PLACES_DATA_FROM_API = "GET_PLACES_DATA_FROM_API";